name: CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '.github/**'
      - 'laravel-projects/**'
  pull_request:
    paths:
      - '.github/**'
      - 'laravel-projects/**'
  workflow_dispatch:

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      task_manager: ${{ steps.filter.outputs.task_manager }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            task_manager:
              - 'laravel-projects/task-manager/**'
              - '.github/actions/setup-laravel/**'
              - '.github/workflows/ci.yml'

  task-manager:
    name: Task Manager Tests
    needs: changes
    if: needs.changes.outputs.task_manager == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      APP_ENV: testing
      APP_DEBUG: false
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite
      CACHE_DRIVER: array
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync
      MAIL_MAILER: log
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare dependencies
        uses: ./.github/actions/setup-laravel
        with:
          project-path: laravel-projects/task-manager
          php-version: '8.3'

      - name: Copy environment file
        run: |
          cp .env.example .env
        working-directory: laravel-projects/task-manager

      - name: Ensure SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite
        working-directory: laravel-projects/task-manager

      - name: Generate application key
        run: php artisan key:generate --force
        working-directory: laravel-projects/task-manager

      - name: Build assets
        run: bun run build
        working-directory: laravel-projects/task-manager

      - name: Run migrations
        run: php artisan migrate --no-interaction --database=sqlite
        working-directory: laravel-projects/task-manager

      - name: Run tests
        run: php artisan test
        working-directory: laravel-projects/task-manager
